//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projections()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ProjectionID { get; set; }
        public int MovieID { get; set; }
        public int CinemaHallID { get; set; }
        public System.DateTime DateTimeStart { get; set; }
        public int TechnologyTypeID { get; set; }
        public decimal TicketPrice { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CinemaHalls CinemaHalls { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual TechnologyTypes TechnologyTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
