// <auto-generated />
namespace CondorExtreme3.Migrations.CondorDBContextChild
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateReservationsModelsLocalDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateReservationsModelsLocalDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201801081541398_UpdateReservationsModelsLocalDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
