//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaglavlje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaglavlje()
        {
            this.Stavke = new HashSet<Stavke>();
        }
    
        public int ZaglavljeId { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<bool> Knjizen { get; set; }
        public Nullable<int> FiskalniRacun { get; set; }
        public Nullable<int> ReklamiraniRacun { get; set; }
        public Nullable<int> ZaposlenikID { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke> Stavke { get; set; }
    }
}
