//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seats()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int SeatID { get; set; }
        public int SeatRowID { get; set; }
        public int SeatColumnID { get; set; }
        public int CinemaHallID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CinemaHalls CinemaHalls { get; set; }
        public virtual SeatColumns SeatColumns { get; set; }
        public virtual SeatRows SeatRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
