//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaCoordinates
    {
        public int CinemaID { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
    
        public virtual Cinemas Cinemas { get; set; }
    }
}
