//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.MovieRatings = new HashSet<MovieRatings>();
            this.MovieRoles = new HashSet<MovieRoles>();
            this.Projections = new HashSet<Projections>();
        }
    
        public int MovieID { get; set; }
        public string Name { get; set; }
        public string OriginalName { get; set; }
        public int GenreID { get; set; }
        public int DurationInMinutes { get; set; }
        public Nullable<int> AgeRestrictionID { get; set; }
        public int MovieDirectorID { get; set; }
        public string Trailer { get; set; }
        public bool IsCurrent { get; set; }
        public bool IsDeleted { get; set; }
        public int ReleaseYear { get; set; }
        public string Synopsis { get; set; }
        public byte[] ImageThumb { get; set; }
        public byte[] PictureBytes { get; set; }
    
        public virtual AgeRestrictions AgeRestrictions { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual MovieDirectors MovieDirectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieRatings> MovieRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieRoles> MovieRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projections> Projections { get; set; }
    }
}
