//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikli()
        {
            this.Cjenovnik = new HashSet<Cjenovnik>();
        }
    
        public int AritkalId { get; set; }
        public int GrupaId { get; set; }
        public string Naziv { get; set; }
        public string JedMjere { get; set; }
        public string Barcode { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cjenovnik> Cjenovnik { get; set; }
    }
}
