//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cjenovnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cjenovnik()
        {
            this.Stavke = new HashSet<Stavke>();
        }
    
        public int CjenovnikId { get; set; }
        public int GrupaId { get; set; }
        public int ArtikalId { get; set; }
        public int Koliciina { get; set; }
        public decimal Cijena { get; set; }
    
        public virtual Artikli Artikli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke> Stavke { get; set; }
    }
}
