//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRoles
    {
        public int RoleID { get; set; }
        public int EmployeeID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
