//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePayments
    {
        public int EmployeePaymentID { get; set; }
        public int EmploymentID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Employments Employments { get; set; }
    }
}
