//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employments()
        {
            this.EmployeePayments = new HashSet<EmployeePayments>();
        }
    
        public int EmploymentID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime HireDate { get; set; }
        public decimal CurrentSalary { get; set; }
        public int EmploymentTypeID { get; set; }
        public string BankAccountNumber { get; set; }
        public int BankID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Banks Banks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePayments> EmployeePayments { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual EmploymentTypes EmploymentTypes { get; set; }
    }
}
