//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservations()
        {
            this.Stavke = new HashSet<Stavke>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ReservationID { get; set; }
        public System.DateTime InitialDate { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public string PhoneNumberVis { get; set; }
        public Nullable<int> RVisitorID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public int IsCompleted { get; set; }
        public Nullable<int> CreditCardNumber { get; set; }
        public Nullable<int> ProjectionID { get; set; }
    
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual RVisitors RVisitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke> Stavke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
