//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke
    {
        public int StavkaId { get; set; }
        public Nullable<int> ZaglavljeId { get; set; }
        public Nullable<int> CijenovnikId { get; set; }
        public int Kolicina { get; set; }
        public Nullable<decimal> Rabat { get; set; }
        public decimal Cijena { get; set; }
        public decimal PDV { get; set; }
        public decimal Iznos { get; set; }
        public Nullable<int> RezervacijaID { get; set; }
    
        public virtual Reservations Reservations { get; set; }
        public virtual Cjenovnik Cjenovnik { get; set; }
        public virtual Zaglavlje Zaglavlje { get; set; }
    }
}
