//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondorExtreme3_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ProjectionID { get; set; }
        public int SeatID { get; set; }
        public decimal TicketPrice { get; set; }
        public int TicketNumber { get; set; }
        public int ReservationID { get; set; }
    
        public virtual Projections Projections { get; set; }
        public virtual Reservations Reservations { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
